blog/views/auth.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import current_user, login_user, logout_user
from werkzeug.urls import url_parse

from blog.forms.forms import UserLogin, UserRegistrationForm
from blog.database.models import User
from blog.database.db import data


auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = UserLogin()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None or not user.verify_password(form.password.data):
            flash("Email ou senha invalidos")
            return redirect(url_for('auth.login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('main.index')
            return redirect(next_page)
    return render_template('auth/login.html', title="Entrar", form=form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@auth.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = UserRegistrationForm()
    if form.validate_on_submit():
        user = User(full_name=form.full_name.data, email=form.email.data,
                    username=form.username.data,password=form.password.data,
                    admin=form.admin.data)
        data.session.add(user)
        data.session.commit()
        flash('Parabens por ingressar no blog')
        return redirect(url_for('auth.login'))

    return render_template('auth/register.html', title='Cadastre-se', form=form)

blog/views/posts.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_required, current_user

from blog.database.models import Post, Category
from blog.database.db import data
from blog.forms.forms import CreateNewPostForm

posts_bp = Blueprint('posts', __name__)

@posts_bp.route('/post/<int:id>/<string:slug>', methods=['GET'])
def post_detail(id, slug):
    post = Post.query.filter_by(id=id).first()
    categories = Category.query.all()
    return render_template('post_detail.html', post=post, categories=categories)

@posts_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
def post_create():
    form = CreateNewPostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, user_id=current_user.id,abstract=form.abstract.data, content=form.content.data, category_id=form.category.data.id)
        data.session.add(post)
        data.session.commit()
        flash("Post Criado com sucesso")
        return redirect(url_for('main.index'))
    return render_template('post_detail.html', title="Crie um novo Post", form=form)

@posts_bp.route('/post/category/<string:name>', methods=['GET'])
def post_category(name):
    # Busca todos os posts por categoria
    page = request.args.get('page', 1, type=int)

    category = Category.query.filter_by(name=name).first()

    posts = Post.query.filter_by(category_id=category.id).order_by(Post.created.desc()).paginate(page=page, per_page=5, error_out=False)

    next_url = url_for('posts.post_category', name=category.name, page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('posts.post_category', name=category.name, page=posts.prev_num) \
        if posts.has_prev else None

    categories = Category.query.all()
    return render_template('post_category.html', posts=posts.items, category=category, categories=categories, next_url=next_url, prev_url=prev_url)

blog/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        {% block head %}
        <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.1/assets/img/favicons/favicon.ico">

    <title>{% block title %} Techster - Technological Blog {% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.1/examples/blog/">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">

    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/blog.css')}}" rel="stylesheet">
    {% endblock %}
</head>
<body>
    {% block body %}
    <div class="container">
        <header class="blog-header py-3">
            {% block header %}
            <div class="row flex-nowrap justify-content-between align-items-center">
              <div class="col-4 pt-1">
                <a class="text-muted" href="#">Subscribe</a>
              </div>
              <div class="col-4 text-center">
                <a class="blog-header-logo text-dark" href="{{url_for('main.index')}}">Techster</a>
              </div>
              <div class="col-4 d-flex justify-content-end align-items-center">
                <a class="text-muted" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
                </a>
                {% if current_user.is_authenticated %}
                <div class="justify-content-between align-items-center">

                  <span>Olá {{ current_user.full_name }}!</span>
                  <a class="btn btn-sm btn-outline-secondary" href="{{url_for('auth.logout')}}">Logout</a>
                </div>
                {% else %}
                <a href="{{url_for('auth.login')}}" class="btn btn-sm btn-outline-secondary">
                  Sign In
                </a>
                {% endif %}
              </div>
            </div>
            {% endblock header %}
          </header>
          <div class="nav-scroller py-1 mb-2">
              {% block categories %}
            <nav class="nav d-flex justify-content-between">
                {% for category in categories %}
                <a class="p-2 text-muted" href="{{url_for('posts.post_category', name=category.name|string)}}">{{category.name}}</a>
                {% endfor %}
              </nav>
              {% endblock %}
          </div>
    
          <!-- <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
            <div class="col-md-6 px-0">
              <h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
              <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what's most interesting in this post's contents.</p>
              <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
            </div>
          </div>
    
          <div class="row mb-2">
            <div class="col-md-6">
              <div class="card flex-md-row mb-4 shadow-sm h-md-250">
                <div class="card-body d-flex flex-column align-items-start">
                  <strong class="d-inline-block mb-2 text-primary">World</strong>
                  <h3 class="mb-0">
                    <a class="text-dark" href="#">Featured post</a>
                  </h3>
                  <div class="mb-1 text-muted">Nov 12</div>
                  <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                  <a href="#">Continue reading</a>
                </div>
                <img class="card-img-right flex-auto d-none d-lg-block" data-src="holder.js/200x250?theme=thumb" alt="Card image cap">
              </div>
            </div>
            <div class="col-md-6">
              <div class="card flex-md-row mb-4 shadow-sm h-md-250">
                <div class="card-body d-flex flex-column align-items-start">
                  <strong class="d-inline-block mb-2 text-success">Design</strong>
                  <h3 class="mb-0">
                    <a class="text-dark" href="#">Post title</a>
                  </h3>
                  <div class="mb-1 text-muted">Nov 11</div>
                  <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                  <a href="#">Continue reading</a>
                </div>
                <img class="card-img-right flex-auto d-none d-lg-block" data-src="holder.js/200x250?theme=thumb" alt="Card image cap">
              </div>
            </div>
          </div> -->
    </div>
    <main role="main" class="container">
        {% block main %}
        <div class="row">
          {% block content %}
          {% endblock content %}
          {% block sidebar %}
                  <aside class="col-md-4 blog-sidebar">
                      <div class="p-3 mb-3 bg-light rounded">
                        <h4 class="font-italic">About</h4>
                        <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
                      </div>
            
                      <div class="p-3">
                        <h4 class="font-italic">Elsewhere</h4>
                        <ol class="list-unstyled">
                          <li><a href="#">GitHub</a></li>
                          <li><a href="#">Twitter</a></li>
                          <li><a href="#">Facebook</a></li>
                        </ol>
                      </div>
                    </aside><!-- /.blog-sidebar -->
                    {% endblock sidebar %}
                  </div>          
        {% endblock main %}
    </main>
    <footer class="blog-footer">
        {% block footer %}
        <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
        <p>
          <a href="#">Back to top</a>
        </p>
        {% endblock footer %}
      </footer>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>
{% endblock %}
</body>
</html>

blog/templates/index.html
{% extends 'base.html' %}
          
    
{% block content %}

        <div class="col-md-8 blog-main">
          <h3 class="pb-3 mb-4 font-italic border-bottom">
            Últimas Publicações
          </h3>
          {% for post in posts %}
          <div class="blog-post">
            <span class="text-primary">{{post.category.name}}</span>
            <h2 class="blog-post-title">{{post.title}}</h2>
            <p class="blog-post-meta">{{post.created.strftime('%m/%d/%Y, %H:%M')}} by <a href="#">{{post.user.full_name}}</a></p>

            {{post.abstract}}
            <a href="{{url_for('posts.post_detail', id=post.id|int, slug=post.slug)}}">Continue reading</a>
          </div>
          <hr>
          {% endfor %}

            <nav class="blog-pagination">
              {% if prev_url %}
              <a class="btn btn-outline-primary" href="{{prev_url}}">Previous</a>
              {% endif %}
              {% if next_url %}
              <a class="btn btn-outline-secondary" href="{{next_url}}">Next</a>
              {% endif %}
            </nav>

        </div>
        {% endblock content %}

blog/templates/post_category.html
{% extends 'base.html' %}
          
    
          <!-- <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
            <div class="col-md-6 px-0">
              <h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
              <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what's most interesting in this post's contents.</p>
              <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
            </div>
          </div>
    
          <div class="row mb-2">
            <div class="col-md-6">
              <div class="card flex-md-row mb-4 shadow-sm h-md-250">
                <div class="card-body d-flex flex-column align-items-start">
                  <strong class="d-inline-block mb-2 text-primary">World</strong>
                  <h3 class="mb-0">
                    <a class="text-dark" href="#">Featured post</a>
                  </h3>
                  <div class="mb-1 text-muted">Nov 12</div>
                  <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                  <a href="#">Continue reading</a>
                </div>
                <img class="card-img-right flex-auto d-none d-lg-block" data-src="holder.js/200x250?theme=thumb" alt="Card image cap">
              </div>
            </div>
            <div class="col-md-6">
              <div class="card flex-md-row mb-4 shadow-sm h-md-250">
                <div class="card-body d-flex flex-column align-items-start">
                  <strong class="d-inline-block mb-2 text-success">Design</strong>
                  <h3 class="mb-0">
                    <a class="text-dark" href="#">Post title</a>
                  </h3>
                  <div class="mb-1 text-muted">Nov 11</div>
                  <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                  <a href="#">Continue reading</a>
                </div>
                <img class="card-img-right flex-auto d-none d-lg-block" data-src="holder.js/200x250?theme=thumb" alt="Card image cap">
              </div>
            </div>
          </div> -->
        {% block content %}
        <div class="col-md-8 blog-main">
          <h3 class="pb-3 mb-4 font-italic border-bottom">
            Todos as publicações sobre: <b>{{category.name}}</b>
          </h3>
          {% for post in posts %}
          <div class="blog-post">
            <span class="text-primary">{{post.category.name}}</span>
            <h2 class="blog-post-title">{{post.title}}</h2>
            <p class="blog-post-meta">{{post.created.strftime('%m/%d/%Y, %H:%M')}} by <a href="#">{{post.user.full_name}}</a></p>

            {{post.abstract}}
            <a href="{{url_for('posts.post_detail', id=post.id|int, slug=post.slug)}}">Continue reading</a>
          </div><!-- /.blog-post -->
          <hr>
          {% endfor %}

          <nav class="blog-pagination">
            {% if prev_url %}
            <a class="btn btn-outline-primary" href="{{prev_url}}">Previous</a>
            {% endif %}
            {% if next_url %}
            <a class="btn btn-outline-secondary" href="{{next_url}}">Next</a>
            {% endif %}
          </nav>

        </div><!-- /.blog-main -->
        {% endblock content %}

blog/templates/post_detail.html
{% extends 'base.html' %}
          
    
          <!-- <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
            <div class="col-md-6 px-0">
              <h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
              <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what's most interesting in this post's contents.</p>
              <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
            </div>
          </div>
    
          <div class="row mb-2">
            <div class="col-md-6">
              <div class="card flex-md-row mb-4 shadow-sm h-md-250">
                <div class="card-body d-flex flex-column align-items-start">
                  <strong class="d-inline-block mb-2 text-primary">World</strong>
                  <h3 class="mb-0">
                    <a class="text-dark" href="#">Featured post</a>
                  </h3>
                  <div class="mb-1 text-muted">Nov 12</div>
                  <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                  <a href="#">Continue reading</a>
                </div>
                <img class="card-img-right flex-auto d-none d-lg-block" data-src="holder.js/200x250?theme=thumb" alt="Card image cap">
              </div>
            </div>
            <div class="col-md-6">
              <div class="card flex-md-row mb-4 shadow-sm h-md-250">
                <div class="card-body d-flex flex-column align-items-start">
                  <strong class="d-inline-block mb-2 text-success">Design</strong>
                  <h3 class="mb-0">
                    <a class="text-dark" href="#">Post title</a>
                  </h3>
                  <div class="mb-1 text-muted">Nov 11</div>
                  <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                  <a href="#">Continue reading</a>
                </div>
                <img class="card-img-right flex-auto d-none d-lg-block" data-src="holder.js/200x250?theme=thumb" alt="Card image cap">
              </div>
            </div>
          </div> -->
        {% block content %}
        <div class="col-md-8 blog-main">
          <div class="blog-post">
            <h2 class="blog-post-title">{{post.title}}</h2>
            <p class="blog-post-meta">{{post.created.strftime('%m/%d/%Y, %H:%M')}} by <a href="#">{{post.user.full_name}}</a></p>

            {{ post.content | safe }}
          </div><!-- /.blog-post -->
          <hr>

        </div><!-- /.blog-main -->
        {% endblock content %}